
# Конфигурация аналитического проекта
project:
  name: "Analytics Course Chapter 23"
  version: "1.0.0"
  description: "Презентация результатов: storytelling, отчёты"
  created_date: "2025-09-04"

# Настройки данных
data:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
  external_data_path: "data/external/"

  # Форматы файлов
  csv_separator: ";"
  decimal_separator: ","
  date_format: "%Y-%m-%d"
  encoding: "utf-8-sig"

  # Ограничения по размеру файлов (в MB)
  max_file_size: 100

# Настройки визуализации
visualization:
  # Цветовая палитра
  colors:
    primary: "#1E3A8A"
    success: "#10B981"
    warning: "#F59E0B"
    danger: "#EF4444"
    info: "#8B5CF6"
    neutral: "#6B7280"
    background: "#FFFFFF"

  # Размеры графиков
  figure_size: [12, 8]
  dpi: 300
  font_size: 12
  title_font_size: 16

  # Стили для разных типов графиков
  chart_styles:
    line_width: 3
    marker_size: 6
    bar_width: 0.8
    transparency: 0.8

# Power BI настройки  
powerbi:
  workspace_name: "Analytics Course"
  theme_file: "corporate_theme.json"
  refresh_frequency: "daily"

  # Настройки производительности
  max_rows_per_table: 1000000
  enable_incremental_refresh: true
  cache_duration_hours: 24

# Git настройки
git:
  # Ветки
  main_branch: "main"
  develop_branch: "develop"
  feature_prefix: "feature/"
  hotfix_prefix: "hotfix/"

  # Коммиты
  commit_types:
    - "feat"    # новая функциональность
    - "fix"     # исправление ошибок
    - "data"    # обновление данных
    - "viz"     # изменения визуализации
    - "docs"    # документация
    - "config"  # конфигурация
    - "test"    # тесты

# Настройки измерения эффективности
metrics:
  # Метрики использования
  tracking_enabled: true

  # Целевые показатели
  target_engagement_score: 70
  target_satisfaction_score: 4.0
  target_time_to_decision_days: 3
  target_implementation_rate: 0.8

  # A/B тестирование
  ab_test_settings:
    min_sample_size: 30
    significance_level: 0.05
    power: 0.8

# Уведомления и алерты
alerts:
  email_notifications: true
  slack_webhook_url: ""  # заполнить при необходимости

  # Условия для алертов
  low_engagement_threshold: 50
  high_error_rate_threshold: 0.05
  data_freshness_hours: 24

# Логирование
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/analytics.log"
  max_file_size_mb: 10
  backup_count: 5

# Безопасность
security:
  # Данные которые нельзя коммитить
  sensitive_patterns:
    - "password"
    - "api_key"
    - "secret"
    - "token"
    - "credentials"

  # Максимальный размер файла для коммита (MB)
  max_commit_file_size: 50

  # Проверка на конфиденциальные данные
  check_pii: true
  pii_patterns:
    - "\b\d{4}-\d{4}-\d{4}-\d{4}\b"  # номера карт
    - "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"  # email
    - "\b\+7\d{10}\b"  # российские телефоны

# Производительность
performance:
  # Настройки для обработки больших данных
  chunk_size: 10000
  memory_limit_gb: 8
  parallel_processing: true
  max_workers: 4

  # Кэширование
  cache_enabled: true
  cache_ttl_hours: 6
